/* Azershal Japanese — content database.
   Concise, business-focused. Each entry: jp, reading (romaji-free, kana), en, [ex], [ex_en], tag.
   Tags: N5/N4/N3/N2 grammar level; vocab categories below.
*/

// ---------- HIRAGANA & KATAKANA ----------
const HIRAGANA = {
  vowels:["あ:a","い:i","う:u","え:e","お:o"],
  k:["か:ka","き:ki","く:ku","け:ke","こ:ko"],
  s:["さ:sa","し:shi","す:su","せ:se","そ:so"],
  t:["た:ta","ち:chi","つ:tsu","て:te","と:to"],
  n:["な:na","に:ni","ぬ:nu","ね:ne","の:no"],
  h:["は:ha","ひ:hi","ふ:fu","へ:he","ほ:ho"],
  m:["ま:ma","み:mi","む:mu","め:me","も:mo"],
  y:["や:ya","ゆ:yu","よ:yo"],
  r:["ら:ra","り:ri","る:ru","れ:re","ろ:ro"],
  w:["わ:wa","を:wo","ん:n"],
  d:["が:ga","ぎ:gi","ぐ:gu","げ:ge","ご:go"],
  z:["ざ:za","じ:ji","ず:zu","ぜ:ze","ぞ:zo"],
  p:["だ:da","ぢ:ji","づ:zu","で:de","ど:do"],
  b:["ば:ba","び:bi","ぶ:bu","べ:be","ぼ:bo"],
  x:["ぱ:pa","ぴ:pi","ぷ:pu","ぺ:pe","ぽ:po"]
};
const KATAKANA = {
  vowels:["ア:a","イ:i","ウ:u","エ:e","オ:o"],
  k:["カ:ka","キ:ki","ク:ku","ケ:ke","コ:ko"],
  s:["サ:sa","シ:shi","ス:su","セ:se","ソ:so"],
  t:["タ:ta","チ:chi","ツ:tsu","テ:te","ト:to"],
  n:["ナ:na","ニ:ni","ヌ:nu","ネ:ne","ノ:no"],
  h:["ハ:ha","ヒ:hi","フ:fu","ヘ:he","ホ:ho"],
  m:["マ:ma","ミ:mi","ム:mu","メ:me","モ:mo"],
  y:["ヤ:ya","ユ:yu","ヨ:yo"],
  r:["ラ:ra","リ:ri","ル:ru","レ:re","ロ:ro"],
  w:["ワ:wa","ヲ:wo","ン:n"],
  d:["ガ:ga","ギ:gi","グ:gu","ゲ:ge","ゴ:go"],
  z:["ザ:za","ジ:ji","ズ:zu","ゼ:ze","ゾ:zo"],
  p:["ダ:da","ヂ:ji","ヅ:zu","デ:de","ド:do"],
  b:["バ:ba","ビ:bi","ブ:bu","ベ:be","ボ:bo"],
  x:["パ:pa","ピ:pi","プ:pu","ペ:pe","ポ:po"]
};

// ---------- BUSINESS VOCAB (flashcard deck) ----------
// cat: meeting | office | finance | email | general
const VOCAB = [
  // Meetings
  {jp:"会議",reading:"かいぎ",en:"meeting",cat:"meeting",jlpt:"N4",
    ex:"会議は三時から始まります。",ex_en:"The meeting starts at 3:00."},
  {jp:"資料",reading:"しりょう",en:"materials / documents",cat:"meeting",jlpt:"N3",
    ex:"会議の資料を準備しました。",ex_en:"I prepared the meeting materials."},
  {jp:"議事録",reading:"ぎじろく",en:"meeting minutes",cat:"meeting",jlpt:"N2",
    ex:"議事録をまとめてください。",ex_en:"Please compile the minutes."},
  {jp:"出席",reading:"しゅっせき",en:"attendance",cat:"meeting",jlpt:"N3",
    ex:"明日の会議に出席します。",ex_en:"I will attend tomorrow's meeting."},
  {jp:"欠席",reading:"けっせき",en:"absence",cat:"meeting",jlpt:"N3",
    ex:"田中さんは欠席です。",ex_en:"Mr. Tanaka is absent."},
  {jp:"議題",reading:"ぎだい",en:"agenda item",cat:"meeting",jlpt:"N2",
    ex:"今日の議題は三つです。",ex_en:"There are three agenda items today."},
  {jp:"意見",reading:"いけん",en:"opinion",cat:"meeting",jlpt:"N4",
    ex:"意見をお聞かせください。",ex_en:"Please share your opinion."},
  {jp:"決定",reading:"けってい",en:"decision",cat:"meeting",jlpt:"N3",
    ex:"決定を下します。",ex_en:"We will make a decision."},
  {jp:"承認",reading:"しょうにん",en:"approval",cat:"meeting",jlpt:"N2",
    ex:"企画の承認をお願いします。",ex_en:"Please approve the plan."},
  {jp:"提案",reading:"ていあん",en:"proposal",cat:"meeting",jlpt:"N2",
    ex:"新しい提案があります。",ex_en:"I have a new proposal."},
  {jp:"報告",reading:"ほうこく",en:"report",cat:"meeting",jlpt:"N3",
    ex:"営業の報告をします。",ex_en:"I'll give the sales report."},
  {jp:"確認",reading:"かくにん",en:"confirmation",cat:"meeting",jlpt:"N4",
    ex:"確認させてください。",ex_en:"Let me confirm."},
  {jp:"検討",reading:"けんとう",en:"consideration / study",cat:"meeting",jlpt:"N2",
    ex:"検討します。",ex_en:"We will consider it."},
  {jp:"延期",reading:"えんき",en:"postponement",cat:"meeting",jlpt:"N2",
    ex:"会議を延期します。",ex_en:"We'll postpone the meeting."},
  {jp:"対象",reading:"たいしょう",en:"target / subject",cat:"meeting",jlpt:"N3",
    ex:"対象は関東地域です。",ex_en:"The target is the Kanto region."},

  // Office
  {jp:"会社",reading:"かいしゃ",en:"company",cat:"office",jlpt:"N5",
    ex:"会社は東京にあります。",ex_en:"The company is in Tokyo."},
  {jp:"社員",reading:"しゃいん",en:"employee",cat:"office",jlpt:"N4",
    ex:"社員は三百人です。",ex_en:"There are 300 employees."},
  {jp:"上司",reading:"じょうし",en:"boss / superior",cat:"office",jlpt:"N3",
    ex:"上司に報告します。",ex_en:"I report to my boss."},
  {jp:"部下",reading:"ぶか",en:"subordinate",cat:"office",jlpt:"N3",
    ex:"部下を指導します。",ex_en:"I supervise my subordinates."},
  {jp:"部署",reading:"ぶしょ",en:"department",cat:"office",jlpt:"N3",
    ex:"どの部署にお勤めですか。",ex_en:"Which department do you work in?"},
  {jp:"課長",reading:"かちょう",en:"section manager",cat:"office",jlpt:"N3",
    ex:"田中課長、お疲れ様です。",ex_en:"Section Manager Tanaka, good work."},
  {jp:"部長",reading:"ぶちょう",en:"department head",cat:"office",jlpt:"N3",
    ex:"部長にご相談したいです。",ex_en:"I'd like to consult the department head."},
  {jp:"社長",reading:"しゃちょう",en:"company president",cat:"office",jlpt:"N4",
    ex:"社長が挨拶しました。",ex_en:"The president gave a greeting."},
  {jp:"取引先",reading:"とりひきさき",en:"client / business partner",cat:"office",jlpt:"N3",
    ex:"取引先を訪問します。",ex_en:"I'll visit a client."},
  {jp:"同僚",reading:"どうりょう",en:"colleague",cat:"office",jlpt:"N3",
    ex:"同僚と昼ごはんを食べます。",ex_en:"I eat lunch with a colleague."},
  {jp:"仕事",reading:"しごと",en:"work / job",cat:"office",jlpt:"N5",
    ex:"仕事が忙しいです。",ex_en:"Work is busy."},
  {jp:"残業",reading:"ざんぎょう",en:"overtime",cat:"office",jlpt:"N3",
    ex:"今日は残業があります。",ex_en:"I have overtime today."},
  {jp:"出張",reading:"しゅっちょう",en:"business trip",cat:"office",jlpt:"N3",
    ex:"大阪へ出張します。",ex_en:"I'm going on a business trip to Osaka."},
  {jp:"勤務",reading:"きんむ",en:"work / duty",cat:"office",jlpt:"N3",
    ex:"勤務時間は九時からです。",ex_en:"Work hours start at 9:00."},
  {jp:"採用",reading:"さいよう",en:"hiring / recruitment",cat:"office",jlpt:"N2",
    ex:"来月、採用面接をします。",ex_en:"We'll hold hiring interviews next month."},
  {jp:"面接",reading:"めんせつ",en:"interview",cat:"office",jlpt:"N3",
    ex:"面接は来週です。",ex_en:"The interview is next week."},
  {jp:"研修",reading:"けんしゅう",en:"training",cat:"office",jlpt:"N3",
    ex:"新入社員研修があります。",ex_en:"There's new-employee training."},
  {jp:"責任",reading:"せきにん",en:"responsibility",cat:"office",jlpt:"N3",
    ex:"責任を持って行います。",ex_en:"I'll do it responsibly."},
  {jp:"担当",reading:"たんとう",en:"in charge of",cat:"office",jlpt:"N3",
    ex:"営業を担当しています。",ex_en:"I'm in charge of sales."},
  {jp:"忙しい",reading:"いそがしい",en:"busy",cat:"office",jlpt:"N5",
    ex:"今、ちょっと手が離せません。",ex_en:"I'm a bit tied up right now."},

  // Finance / numbers / trade
  {jp:"売上",reading:"うりあげ",en:"sales / revenue",cat:"finance",jlpt:"N2",
    ex:"売上は前年比10%増です。",ex_en:"Sales are up 10% year-on-year."},
  {jp:"利益",reading:"りえき",en:"profit",cat:"finance",jlpt:"N3",
    ex:"利益が減りました。",ex_en:"Profit decreased."},
  {jp:"経費",reading:"けいひ",en:"expenses",cat:"finance",jlpt:"N2",
    ex:"経費を削減します。",ex_en:"We'll cut expenses."},
  {jp:"予算",reading:"よさん",en:"budget",cat:"finance",jlpt:"N3",
    ex:"予算内に収めます。",ex_en:"We'll keep it within budget."},
  {jp:"契約",reading:"けいやく",en:"contract",cat:"finance",jlpt:"N3",
    ex:"契約を結びます。",ex_en:"We'll sign a contract."},
  {jp:"見積もり",reading:"みつもり",en:"estimate / quote",cat:"finance",jlpt:"N3",
    ex:"見積もりを送ります。",ex_en:"I'll send a quote."},
  {jp:"請求書",reading:"せいきゅうしょ",en:"invoice",cat:"finance",jlpt:"N2",
    ex:"請求書を発行しました。",ex_en:"We issued the invoice."},
  {jp:"領収書",reading:"りょうしゅうしょ",en:"receipt",cat:"finance",jlpt:"N2",
    ex:"領収書をいただけますか。",ex_en:"May I have a receipt?"},
  {jp:"支払い",reading:"しはらい",en:"payment",cat:"finance",jlpt:"N3",
    ex:"支払いは月末です。",ex_en:"Payment is at month-end."},
  {jp:"価格",reading:"かかく",en:"price",cat:"finance",jlpt:"N3",
    ex:"価格を相談しましょう。",ex_en:"Let's discuss the price."},
  {jp:"割引",reading:"わりびき",en:"discount",cat:"finance",jlpt:"N3",
    ex:"割引は可能ですか。",ex_en:"Is a discount possible?"},
  {jp:"納期",reading:"のうき",en:"delivery date",cat:"finance",jlpt:"N2",
    ex:"納期は来月末です。",ex_en:"Delivery is end of next month."},
  {jp:"在庫",reading:"ざいこ",en:"inventory / stock",cat:"finance",jlpt:"N2",
    ex:"在庫がありません。",ex_en:"We're out of stock."},
  {jp:"注文",reading:"ちゅうもん",en:"order",cat:"finance",jlpt:"N4",
    ex:"注文を確認しました。",ex_en:"We confirmed the order."},
  {jp:"返品",reading:"へんぴん",en:"return (goods)",cat:"finance",jlpt:"N2",
    ex:"返品は可能です。",ex_en:"Returns are possible."},

  // Email / communication
  {jp:"御社",reading:"おんしゃ",en:"your company (spoken)",cat:"email",jlpt:"N2",
    ex:"御社のサービスについて伺います。",ex_en:"I'd like to ask about your company's service."},
  {jp:"弊社",reading:"へいしゃ",en:"our company (humble)",cat:"email",jlpt:"N2",
    ex:"弊社の製品をご紹介します。",ex_en:"Let me introduce our company's products."},
  {jp:"担当者",reading:"たんとうしゃ",en:"person in charge",cat:"email",jlpt:"N3",
    ex:"担当者にお取り次ぎください。",ex_en:"Please connect me to the person in charge."},
  {jp:"ご連絡",reading:"ごれんらく",en:"contact (polite)",cat:"email",jlpt:"N3",
    ex:"ご連絡ありがとうございます。",ex_en:"Thank you for your message."},
  {jp:"お礼",reading:"おれい",en:"thanks / gratitude",cat:"email",jlpt:"N3",
    ex:"お礼申し上げます。",ex_en:"I express my gratitude."},
  {jp:"案内",reading:"あんない",en:"guide / information",cat:"email",jlpt:"N4",
    ex:"詳細をご案内します。",ex_en:"I'll guide you through the details."},
  {jp:"返信",reading:"へんしん",en:"reply (email)",cat:"email",jlpt:"N3",
    ex:"返信が遅くなりすみません。",ex_en:"Sorry for the late reply."},
  {jp:"添付",reading:"てんぷ",en:"attachment",cat:"email",jlpt:"N2",
    ex:"資料を添付しました。",ex_en:"I attached the document."},
  {jp:"拝見",reading:"はいけん",en:"see / look at (humble)",cat:"email",jlpt:"N2",
    ex:"メールを拝見しました。",ex_en:"I saw your email (humble)."},
  {jp:"伺う",reading:"うかがう",en:"hear / visit / ask (humble)",cat:"email",jlpt:"N3",
    ex:"意見を伺います。",ex_en:"I'll hear your opinion (humble)."},
  {jp:"申し上げる",reading:"もうしあげる",en:"say / do (humble)",cat:"email",jlpt:"N2",
    ex:"お礼申し上げます。",ex_en:"I humbly express my thanks."},
  {jp:"承知",reading:"しょうち",en:"understand / accept (humble)",cat:"email",jlpt:"N2",
    ex:"承知いたしました。",ex_en:"I understand (formal)."},

  // General business
  {jp:"準備",reading:"じゅんび",en:"preparation",cat:"general",jlpt:"N4",
    ex:"準備ができました。",ex_en:"Preparations are done."},
  {jp:"説明",reading:"せつめい",en:"explanation",cat:"general",jlpt:"N4",
    ex:"ご説明します。",ex_en:"I'll explain."},
  {jp:"質問",reading:"しつもん",en:"question",cat:"general",jlpt:"N5",
    ex:"質問はありますか。",ex_en:"Are there any questions?"},
  {jp:"問題",reading:"もんだい",en:"problem / issue",cat:"general",jlpt:"N5",
    ex:"問題が発生しました。",ex_en:"A problem occurred."},
  {jp:"解決",reading:"かいけつ",en:"solution / resolve",cat:"general",jlpt:"N3",
    ex:"問題を解決します。",ex_en:"We'll solve the problem."},
  {jp:"理由",reading:"りゆう",en:"reason",cat:"general",jlpt:"N4",
    ex:"理由を説明します。",ex_en:"I'll explain the reason."},
  {jp:"目的",reading:"もくてき",en:"purpose",cat:"general",jlpt:"N3",
    ex:"目的を明確にします。",ex_en:"Make the purpose clear."},
  {jp:"予定",reading:"よてい",en:"schedule / plan",cat:"general",jlpt:"N4",
    ex:"明日の予定を教えてください。",ex_en:"Please tell me tomorrow's schedule."},
  {jp:"締め切り",reading:"しめきり",en:"deadline",cat:"general",jlpt:"N3",
    ex:"締め切りは金曜です。",ex_en:"The deadline is Friday."},
  {jp:"間に合う",reading:"まにあう",en:"to make it in time",cat:"general",jlpt:"N3",
    ex:"間に合いますか。",ex_en:"Will we make it in time?"},
  {jp:"急ぐ",reading:"いそぐ",en:"to hurry",cat:"general",jlpt:"N4",
    ex:"少し急いでいます。",ex_en:"I'm in a bit of a hurry."},
  {jp:"努力",reading:"どりょく",en:"effort",cat:"general",jlpt:"N3",
    ex:"努力します。",ex_en:"I'll make an effort."},
  {jp:"改善",reading:"かいぜん",en:"improvement",cat:"general",jlpt:"N2",
    ex:"改善案を提案します。",ex_en:"I propose an improvement plan."},
  {jp:"効率",reading:"こうりつ",en:"efficiency",cat:"general",jlpt:"N2",
    ex:"効率を上げます。",ex_en:"We'll raise efficiency."},
  {jp:"成功",reading:"せいこう",en:"success",cat:"general",jlpt:"N3",
    ex:"プロジェクトは成功しました。",ex_en:"The project succeeded."},
  {jp:"失敗",reading:"しっぱい",en:"failure / mistake",cat:"general",jlpt:"N3",
    ex:"失敗から学びます。",ex_en:"We learn from failure."},
  {jp:"経験",reading:"けいけん",en:"experience",cat:"general",jlpt:"N3",
    ex:"経験が豊富です。",ex_en:"I have rich experience."},
  {jp:"技術",reading:"ぎじゅつ",en:"technology / skill",cat:"general",jlpt:"N3",
    ex:"技術を磨きます。",ex_en:"We hone our skills."},
  {jp:"製品",reading:"せいひん",en:"product",cat:"general",jlpt:"N3",
    ex:"新製品を発表します。",ex_en:"We'll launch a new product."},
  {jp:"市場",reading:"しじょう",en:"market",cat:"general",jlpt:"N2",
    ex:"市場を分析します。",ex_en:"We analyze the market."},

  // Extra high-frequency verbs/adjectives
  {jp:"お疲れ様",reading:"おつかれさま",en:"good work (greeting)",cat:"general",jlpt:"N4",
    ex:"お疲れ様です。",ex_en:"Good work (standard office greeting)."},
  {jp:"よろしくお願いします",reading:"よろしくおねがいします",en:"please / I count on you",cat:"general",jlpt:"N4",
    ex:"今後ともよろしくお願いします。",ex_en:"I look forward to working with you."},
  {jp:"失礼します",reading:"しつれいします",en:"excuse me / I'm intruding",cat:"general",jlpt:"N3",
    ex:"お部屋、失礼します。",ex_en:"Excuse me for entering the room."},
  {jp:"お先に",reading:"おさきに",en:"before you / I'm leaving first",cat:"general",jlpt:"N3",
    ex:"お先に失礼します。",ex_en:"I'm leaving before you (polite)."},
  {jp:"申し訳ありません",reading:"もうしわけありません",en:"I'm very sorry",cat:"general",jlpt:"N3",
    ex:"申し訳ありません、遅れました。",ex_en:"I'm very sorry I'm late."},
  {jp:"恐れ入ります",reading:"おそれいります",en:"excuse me (very polite)",cat:"general",jlpt:"N2",
    ex:"恐れ入りますが、お時間をいただけますか。",ex_en:"Excuse me, but may I have a moment?"},
  {jp:"お世話になっております",reading:"おせわになっております",en:"thank you for your support (to clients)",cat:"general",jlpt:"N2",
    ex:"いつもお世話になっております。",ex_en:"Thank you for your continued support."},
  {jp:"ご苦労様",reading:"ごくろうさま",en:"good work (to subordinates only)",cat:"general",jlpt:"N3",
    ex:"ご苦労様でした。",ex_en:"Good work (use ONLY to subordinates)."},

  // Numbers / counters business-critical
  {jp:"一万",reading:"いちまん",en:"10,000 (万 = myriads)",cat:"finance",jlpt:"N4",
    ex:"価格は一万円です。",ex_en:"The price is 10,000 yen."},
  {jp:"百万",reading:"ひゃくまん",en:"1,000,000",cat:"finance",jlpt:"N3",
    ex:"売上は百万円です。",ex_en:"Sales are 1,000,000 yen."},
  {jp:"一億",reading:"いちおく",en:"100,000,000 (億)",cat:"finance",jlpt:"N2",
    ex:"利益は一億円に達しました。",ex_en:"Profit reached 100,000,000 yen."},
  {jp:"枚",reading:"まい",en:"counter: flat things (sheets)",cat:"finance",jlpt:"N5",
    ex:"資料を三枚ください。",ex_en:"Please give me 3 sheets of material."},
  {jp:"件",reading:"けん",en:"counter: matters / cases",cat:"finance",jlpt:"N3",
    ex:"相談が三件あります。",ex_en:"There are 3 matters to consult."},
  {jp:"〜社",reading:"しゃ",en:"counter: companies",cat:"finance",jlpt:"N3",
    ex:"取引先は五十社です。",ex_en:"We have 50 client companies."},
  {jp:"名",reading:"めい",en:"counter: people (polite)",cat:"finance",jlpt:"N4",
    ex:"出席者は十名です。",ex_en:"There are 10 attendees."}
];

// ---------- KEIGO: 8 core verb trios (regular / sonkeigo-respect / kenjougo-humble) ----------
// These cover ~80% of workplace honorific moments. Highest leverage.
const KEIGO_TRIO = [
  {reg:"行く",regR:"いく",son:"いらっしゃる",sonR:"いらっしゃる",ken:"参る/伺う",kenR:"まいる/うかがう",en:"go",note:"Client いらっしゃる; we 参る/伺う"},
  {reg:"来る",regR:"くる",son:"いらっしゃる/見える",sonR:"いらっしゃる/みえる",ken:"参る",kenR:"まいる",en:"come",note:"Client comes = お見えになる too"},
  {reg:"いる",regR:"いる",son:"いらっしゃる",sonR:"いらっしゃる",ken:"おります",kenR:"おります",en:"be (exist, person)",note:"Own state humble: おります"},
  {reg:"する",regR:"する",son:"なさる",sonR:"なさる",ken:"いたします",kenR:"いたします",en:"do",note:"いたします = humble する"},
  {reg:"言う",regR:"いう",son:"おっしゃる",sonR:"おっしゃる",ken:"申し上げる/申す",kenR:"もうしあげる/もうす",en:"say",note:"申し上げる very formal"},
  {reg:"見る",regR:"みる",son:"ご覧になる",sonR:"ごらんになる",ken:"拝見する",kenR:"はいけんする",en:"see/look",note:"拝見 = humble see"},
  {reg:"聞く",regR:"きく",son:"お聞きになる",sonR:"おききになる",ken:"伺う/拝聴する",kenR:"うかがう/はいちょうする",en:"hear/ask",note:"伺う = hear/visit/ask humble"},
  {reg:"食べる/飲む",regR:"たべる/のむ",son:"召し上がる",sonR:"めしあがる",ken:"いただく",kenR:"いただく",en:"eat/drink",note:"いただく = humble receive"},
  // bonus high-value
  {reg:"会う",regR:"あう",son:"お会いになる",sonR:"おあいになる",ken:"お目にかかる",kenR:"おめにかかる",en:"meet",note:"We humbly meet client"},
  {reg:"思う/知る",regR:"おもう/しる",son:"お思いになる/ご存知",sonR:"ごぞんじ",ken:"存じる",kenR:"ぞんじる",en:"think/know",note:"ご存知 = client knows; 存じる = humble know/think"},
  {reg:"もらう",regR:"もらう",son:"—",sonR:"-",ken:"いただく",kenR:"いただく",en:"receive",note:"Receiving from client = いただく"},
  {reg:"見せる",regR:"みせる",son:"—",sonR:"-",ken:"お目にかける/ご覧に入れる",kenR:"おめにかける",en:"show",note:"We humbly show client"}
];

// Special polite prefixes / structures
const KEIGO_RULES = [
  {t:"尊敬 (sonkeigo)",use:"Raise the CLIENT/SUPERIOR's action",how:"お + V-stem + になる  /  ご + noun + になる  /  special verb (いらっしゃる, おっしゃる)",ex:"お客様がお帰りになりました",ex_en:"The client went home (respect)."},
  {t:"謙譲 (kenjougo)",use:"Lower YOUR action toward a superior",how:"お + V-stem + する  /  ご + noun + する  /  special verb (伺う, いたします)",ex:"明日、伺います",ex_en:"I'll visit you tomorrow (humble)."},
  {t:"丁寧 (teineigo)",use:"Polite distance — safe default",how:"V-masu + です / ます / ござる",ex:"こちらでございます",ex_en:"It is here (polite)."},
  {t:"美化語 (bikago)",use:"Just polite-sounding nouns",how:"お/ご + noun (お茶, ご飯, お電話)",ex:"お電話ありがとうございます",ex_en:"Thank you for the call."},
  {t:"二重敬語 ❌",use:"AVOID: stacking two honorifics",how:"× お伺いいたします (already humble)",ex:"○ 伺います",ex_en:"Don't double-humble."}
];

// Common keigo MISTAKES
const KEIGO_MISTAKES = [
  {bad:"ご苦労様です (to superior)",good:"お疲れ様です",why:"ご苦労様 is top-down only. To superiors/clients use お疲れ様です or forget it with clients."},
  {bad:"わかりました (to client)",good:"承知いたしました / かしこまりました",why:"わかりました is too casual for clients."},
  {bad:"すみません (apology to client)",good:"申し訳ございません",why:"すみません is casual; clients need 申し訳ございません."},
  {bad:"人間が二人です (counting people)",good:"名様でございます",why:"Use 名 for people; never 人間 in business counting."},
  {bad:"自分でやってください (to client)",good:"お客様、こちらでご案内いたします",why:"Direct commands to clients are rude — guide instead."},
  {bad:"ちょうど見ています (client viewing)",good:"ただいまご覧いただいております",why:"Raise the client's action with ご覧になる."},
  {bad:"〜さん to client's name in formal context",good:"〜様 (sama)",why:"Use 様 for clients/customers; さん is internal."},
  {bad:"了解しました (to boss/client)",good:"承知いたしました",why:"了解 is peer-to-peer / military. Never up."}
];

// ---------- PHRASE BANKS ----------
const PHRASES = {
  email:[
    {jp:"いつもお世話になっております。",en:"Thank you for your continued support. (standard opening to clients)"},
    {jp:"〇〇株式会社の〇〇でございます。",en:"I'm XX at XX Co. (self-intro)"},
    {jp:"ご連絡ありがとうございます。",en:"Thank you for your message."},
    {jp:"お忙しいところ恐れ入りますが、",en:"Excuse me while you're busy, but..."},
    {jp:"以下の件についてご相談したく、ご連絡いたしました。",en:"I'm contacting you to consult on the following matter."},
    {jp:"資料を添付いたしますので、ご確認ください。",en:"I've attached the document, please review it."},
    {jp:"ご確認のほど、よろしくお願い申し上げます。",en:"Kindly confirm. (closing)"},
    {jp:"お手数をおかけして申し訳ございません。",en:"Sorry for the trouble."},
    {jp:"ご都合のよい日時をお知らせください。",en:"Please let me know a convenient date/time."},
    {jp:"引き続き、よろしくお願いいたします。",en:"We continue to look forward to working with you. (closing)"},
    {jp:"件名につき、ご報告申し上げます。",en:"I report on the subject matter."},
    {jp:"ご検討のほどよろしくお願いいたします。",en:"We kindly ask for your consideration."},
    {jp:"不明な点がございましたら、お気軽にお問い合わせください。",en:"If anything is unclear, please feel free to ask."},
    {jp:"拝啓 / 敬具",en:"Dear... / Sincerely (formal letter bracket)"},
    {jp:"取り急ぎ、メールにてご連絡まで。",en:"For now, a quick email reply. (light closing)"},
    {jp:"ご返信が遅くなり、申し訳ございません。",en:"Apologies for the delayed reply."},
    {jp:"以上、よろしくお願いいたします。",en:"That's all — thank you. (standard end)"},
    {jp:"ご指定の方法で進めさせていただきます。",en:"I will proceed as you specified."},
    {jp:"社内で確認のうえ、改めてご連絡いたします。",en:"I'll check internally and get back to you."},
    {jp:"お見積もりを送信いたします。",en:"I will send the quote."}
  ],
  meeting:[
    {jp:"本日はお時間をいただき、ありがとうございます。",en:"Thank you for your time today. (opening)"},
    {jp:"さっそくですが、始めさせていただきます。",en:"Without further ado, let's begin."},
    {jp:"本日の議題は三つあります。",en:"There are three agenda items today."},
    {jp:"まず、〇〇についてご報告します。",en:"First, I'll report on XX."},
    {jp:"ご意見をお聞かせいただけますか。",en:"Could you share your opinion?"},
    {jp:"もう少し詳しく説明していただけますか。",en:"Could you explain in a bit more detail?"},
    {jp:"その点について、私は賛成です。",en:"I agree on that point."},
    {jp:"少し懸念があります。",en:"I have some concern."},
    {jp:"案を一つ提案してもよろしいですか。",en:"May I propose an idea?"},
    {jp:"数字で確認させてください。",en:"Let me confirm with the numbers."},
    {jp:"では、次の議題に移ります。",en:"Then, let's move to the next item."},
    {jp:"決定事項をまとめます。",en:"I'll summarize the decisions."},
    {jp:"次回は来週の水曜にいたしました。",en:"The next meeting is set for next Wednesday."},
    {jp:"本日はありがとうございました。",en:"Thank you for today. (closing)"},
    {jp:"今後ともよろしくお願いいたします。",en:"We look forward to your continued cooperation."},
    {jp:"持ち帰り事項は二つです。",en:"There are two action items to follow up."},
    {jp:"ここまでは異論ないですね。",en:"No objections so far, right?"},
    {jp:"時間が来ましたので、終了いたします。",en:"Time is up, so we'll close."},
    {jp:"録画・録音してもよろしいですか。",en:"May I record this?"},
    {jp:"画面を共有させていただきます。",en:"I'll share my screen."}
  ],
  phone:[
    {jp:"おはようございます。〇〇社でございます。",en:"Good morning, XX Company. (answering)"},
    {jp:"お電話ありがとうございます。〇〇でございます。",en:"Thank you for calling, this is XX."},
    {jp:"いつもお世話になっております。",en:"Thank you for your continued support."},
    {jp:"恐れ入りますが、どのようなご用件でしょうか。",en:"Excuse me, what is the matter about?"},
    {jp:"〇〇の担当者にお取り次ぎいただけますか。",en:"Could you connect me to the person in charge of XX?"},
    {jp:"恐れ入りますが、〇〇さんはいらっしゃいますか。",en:"Excuse me, is XX available?"},
    {jp:"ただいま席を外しております。",en:"They are away from their desk right now."},
    {jp:"戻り次第、折り返しご連絡いたします。",en:"I'll have them call you back as soon as they return."},
    {jp:"念のため、お電話番号をいただけますか。",en:"May I have your phone number, just in case?"},
    {jp:"それでは、失礼いたします。",en:"Then, I'll hang up (polite)."},
    {jp:"お電話が遠いのですが、もう一度お願いできますか。",en:"The connection is bad, could you repeat?"},
    {jp:"少々お待ちくださいませ。",en:"Please wait a moment (polite)."},
    {jp:"おつなぎしますので、そのままでお待ちください。",en:"I'll connect you, please hold."},
    {jp:"恐れ入りますが、ご用件を伺ってもよろしいでしょうか。",en:"May I take a message?"},
    {jp:"夕方に再度ご連絡いたします。",en:"I'll contact you again in the evening."}
  ],
  meishi:[
    {jp:"はじめまして、〇〇と申します。",en:"Nice to meet you, I'm XX. (first meeting)"},
    {jp:"こちら、私の名刺でございます。",en:"Here is my card. (offering)"},
    {jp:"頂戴いたします。",en:"I receive it (when taking their card)."},
    {jp:"お名前を拝見いたしますね。",en:"Let me look at your name."},
    {jp:"失礼ですが、お名前は何とお読みすればよろしいでしょうか。",en:"Excuse me, how do you read your name?"},
    {jp:"恐れ入りますが、お名刺をいただけますか。",en:"May I have your card?"},
    {jp:"ご丁寧にありがとうございます。",en:"Thank you for your politeness."},
    {jp:"今後ともよろしくお願いいたします。",en:"I look forward to working with you."}
  ]
};

// ---------- GRAMMAR (N5→N3, business-relevant) ----------
// Each: l (level), t (pattern), en (meaning), ex/ex_en (main example),
//   breakdown (plain-English how-it-works), more (2 extra examples {jp,en}).
const GRAMMAR = [
  {l:"N5",t:"は / が / を / に / で / と / の",en:"Particles: topic / subject / object / target / means / with / possession",
    ex:"私は田中です。会社で働きます。",ex_en:"I'm Tanaka. I work at a company.",
    breakdown:"は marks the topic (what the sentence is about). が marks the subject (the doer). を = direct object. に = target/time/place. で = means/where action happens. と = with/and. の = connects nouns (A's B).",
    more:[{jp:"この資料は田中さんのです。",en:"These materials are Tanaka's."},{jp:"会議は三時に始まります。",en:"The meeting starts at three."}]},
  {l:"N5",t:"〜ます / 〜です (polite)",en:"Polite present/affirmative — default business form",
    ex:"会議は三時に始まります。",ex_en:"The meeting starts at 3.",
    breakdown:"Add ます to a verb stem or です after a noun/na-adjective for polite speech. This is your safe default in any business setting. Negative: 〜ません / 〜じゃありません.",
    more:[{jp:"私は営業担当です。",en:"I'm in charge of sales."},{jp:"会議はまだ始まりません。",en:"The meeting hasn't started yet."}]},
  {l:"N5",t:"〜ました / 〜ませんでした",en:"Polite past / negative past",
    ex:"昨日、会議がありました。",ex_en:"There was a meeting yesterday.",
    breakdown:"ました = polite past affirmative (did). ませんでした = polite past negative (did not). Just attach to the verb stem.",
    more:[{jp:"昨日、資料を送りました。",en:"I sent the materials yesterday."},{jp:"先週は出張しませんでした。",en:"I didn't go on a business trip last week."}]},
  {l:"N5",t:"〜たい / 〜ほしい",en:"Want to do / want (thing)",
    ex:"ご相談したいです。",ex_en:"I want to consult with you.",
    breakdown:"たい attaches to a verb stem = 'want to do (action)'. ほしい = 'want (a thing)'. In business, soften with 〜たいのですが / 〜たいと存じます.",
    more:[{jp:"資料を確認したいです。",en:"I want to check the materials."},{jp:"もっと詳しい情報がほしいです。",en:"I want more detailed information."}]},
  {l:"N5",t:"〜て / 〜ないで",en:"Te-form: connect, request, reason",
    ex:"資料を見てください。",ex_en:"Please look at the materials.",
    breakdown:"The て-form links clauses and is the base for requests (〜てください = please do), permission, and reason. Conjugate each verb group to its て-form (e.g. 見る→見て, 書く→書いて, する→して).",
    more:[{jp:"資料を確認して返信します。",en:"I'll check the materials and reply."},{jp:"もう一度説明してください。",en:"Please explain one more time."}]},
  {l:"N5",t:"〜ている",en:"Ongoing state / continuing action",
    ex:"今、準備しています。",ex_en:"I'm preparing now.",
    breakdown:"ている = action in progress ('am doing') OR a resulting state ('have done and still in that state'). て + いる (the helper verb いる).",
    more:[{jp:"今、会議をしています。",en:"We're in a meeting right now."},{jp:"田中さんは大阪に出張しています。",en:"Tanaka is on a business trip in Osaka."}]},
  {l:"N5",t:"〜から / 〜ので",en:"Because (から casual; ので polite)",
    ex:"会議があるので、早退します。",ex_en:"Because there's a meeting, I'll leave early.",
    breakdown:"Both give a reason, then the result. ので is softer/more polite — preferred in business. から is more direct/casual. Structure: [reason] から/ので [result].",
    more:[{jp:"会議があるから、行けません。",en:"I can't go because there's a meeting."},{jp:"電車が遅延したため、遅れました。",en:"I was late because the train was delayed."}]},
  {l:"N5",t:"〜と (conditional)",en:"If/when — natural consequence",
    ex:"右に曲がると、駅があります。",ex_en:"If you turn right, there's a station.",
    breakdown:"と = 'when/whenever A happens, B naturally follows'. Used for general truths and habitual results. The result cannot be a command or intention.",
    more:[{jp:"ボタンを押すと、画面が出ます。",en:"When you press the button, the screen appears."},{jp:"春になると、桜が咲きます。",en:"When spring comes, the cherry blossoms bloom."}]},
  {l:"N5",t:"〜ましょう",en:"Let's / shall I (polite volitional)",
    ex:"始めましょうか。",ex_en:"Shall we begin?",
    breakdown:"ましょう = polite 'let's do'. With か it becomes a soft suggestion/question ('shall we?'). Attach to the verb stem.",
    more:[{jp:"そろそろ始めましょう。",en:"Let's start soon."},{jp:"ここで休憩しましょうか。",en:"Shall we take a break here?"}]},
  {l:"N5",t:"〜ましょうか (offer)",en:"Shall I do X for you?",
    ex:"お持ちしましょうか。",ex_en:"Shall I carry it for you?",
    breakdown:"ましょうか = offering to do something for the listener ('shall I do X?'). Polite and helpful — common in service/business. Reply: ええ、お願いします / いいえ、結構です.",
    more:[{jp:"コーヒーをお持ちしましょうか。",en:"Shall I bring you coffee?"},{jp:"資料をお送りしましょうか。",en:"Shall I send you the materials?"}]},
  {l:"N5",t:"〜ないといけない",en:"Must do (casual-ish)",
    ex:"資料を準備しないといけません。",ex_en:"I must prepare the materials.",
    breakdown:"ないといけない = 'if not done, it won't do' → must. Polite: 〜ないといけません. Softer business: 〜なければなりません (more formal).",
    more:[{jp:"明日までに返信しないといけません。",en:"I must reply by tomorrow."},{jp:"契約書に署名しなければなりません。",en:"I have to sign the contract."}]},

  {l:"N4",t:"〜てもいいですか",en:"May I do X? (permission)",
    ex:"帰ってもいいですか。",ex_en:"May I go home?",
    breakdown:"て + も + いい = 'it's okay even if I do' → 'may I?'. Asking permission politely. Answer: はい、いいですよ / すみません、ちょっと…",
    more:[{jp:"この資料を見てもいいですか。",en:"May I look at these materials?"},{jp:"早退してもよろしいですか。",en:"May I leave early?"}]},
  {l:"N4",t:"〜てはいけない",en:"Must not do",
    ex:"社外秘なので、話してはいけません。",ex_en:"It's confidential, you must not tell.",
    breakdown:"て + は + いけない = 'must not do'. Prohibition. Polite: 〜てはいけません. Often softened in business to 〜ないでください.",
    more:[{jp:"社外秘を外部に話してはいけません。",en:"You must not tell outsiders about confidential matters."},{jp:"ここで写真を撮ってはいけません。",en:"You must not take photos here."}]},
  {l:"N4",t:"〜ことができる",en:"Can do (formal ability)",
    ex:"英語で説明することができます。",ex_en:"I can explain in English.",
    breakdown:"Verb (plain) + ことができる = 'can do' (more formal than the potential form). Use in business/formal writing. Negative: 〜ことができません.",
    more:[{jp:"日本語でメールを書くことができます。",en:"I can write emails in Japanese."},{jp:"来週は出張できません。",en:"I can't go on a business trip next week."}]},
  {l:"N4",t:"〜たことがある",en:"Have experienced",
    ex:"中国へ出張したことがあります。",ex_en:"I've been to China on business.",
    breakdown:"Past plain (た) + ことがある = 'have the experience of having done X'. Used to talk about things you've done at least once. Negative: 〜たことがありません.",
    more:[{jp:"この製品を使ったことがあります。",en:"I've used this product before."},{jp:"社長に会ったことはありません。",en:"I've never met the president."}]},
  {l:"N4",t:"〜つもり",en:"Intend to",
    ex:"来年転職するつもりです。",ex_en:"I intend to change jobs next year.",
    breakdown:"Plain form + つもりです = 'I intend to do X'. About your own plans, not others'. Negative: 〜ないつもりです (intend not to).",
    more:[{jp:"来月、新しいプロジェクトを始めるつもりです。",en:"I intend to start a new project next month."},{jp:"今期は予算を増やすつもりはありません。",en:"I don't intend to increase the budget this term."}]},
  {l:"N4",t:"〜だろう / 〜でしょう",en:"Probably / conjecture (polite でしょう)",
    ex:"明日は雨でしょう。",ex_en:"It'll probably rain tomorrow.",
    breakdown:"Plain form + でしょう (polite) / だろう (casual) = conjecture ('probably / I suppose'). Softens statements — very useful in business to avoid sounding too direct.",
    more:[{jp:"明日の会議は長くなるでしょう。",en:"Tomorrow's meeting will probably be long."},{jp:"売上は来期も増えるでしょう。",en:"Sales will probably increase next term too."}]},
  {l:"N4",t:"〜ながら",en:"While doing",
    ex:"歩きながら話しましょう。",ex_en:"Let's talk while walking.",
    breakdown:"Stem (ます-form without ます) + ながら = 'while doing X, also do Y'. Two actions happen at the same time; the main action is the second clause.",
    more:[{jp:"資料を見ながら説明します。",en:"I'll explain while looking at the materials."},{jp:"飲みながら会議をするのは失礼です。",en:"Having a meeting while drinking is rude."}]},
  {l:"N4",t:"〜てから",en:"After doing X",
    ex:"確認してから返信します。",ex_en:"I'll reply after confirming.",
    breakdown:"て + から = 'after doing X, then do Y'. Emphasizes the order — X must finish before Y. Different from just て (which links loosely).",
    more:[{jp:"社内で確認してからご連絡します。",en:"I'll contact you after checking internally."},{jp:"契約を読んでから署名してください。",en:"Please read the contract before signing."}]},
  {l:"N4",t:"〜はず",en:"Should be / expected",
    ex:"もう届いているはずです。",ex_en:"It should have arrived already.",
    breakdown:"Plain form + はず = 'it's expected/supposed to be' — based on logic or information. Stronger than でしょう. Negative: 〜ないはずです (should not).",
    more:[{jp:"会議はもう終わっているはずです。",en:"The meeting should be over by now."},{jp:"田中さんはまだ席にいるはずです。",en:"Tanaka should still be at his desk."}]},
  {l:"N4",t:"〜ために",en:"For the purpose of / because of",
    ex:"会議のために資料を作りました。",ex_en:"I made materials for the meeting.",
    breakdown:"Noun + のために or verb (plain) + ために = 'in order to / for the purpose of'. Also 'because of' with a cause. Formal — common in business writing.",
    more:[{jp:"コストを減らすために、経費を見直します。",en:"To cut costs, we'll review expenses."},{jp:"問題解決のために会議を開きます。",en:"We'll hold a meeting to solve the problem."}]},
  {l:"N4",t:"〜のに",en:"Even though (mild complaint)",
    ex:"約束したのに来ませんでした。",ex_en:"They promised but didn't come.",
    breakdown:"Plain form + のに = 'even though X, Y' — expresses surprise/disappointment that the result didn't match expectation. Softer/colloquial; avoid in formal writing.",
    more:[{jp:"予約したのに、部屋がありません。",en:"Even though I reserved, there's no room."},{jp:"何度も説明したのに、わかりません。",en:"Even though I explained many times, they don't understand."}]},
  {l:"N4",t:"受身 (passive)",en:"〜れる/られる — passive / affected",
    ex:"会議は延期されました。",ex_en:"The meeting was postponed.",
    breakdown:"Passive = subject has the action done to it. Group I: 〜れる (書く→書かれる). Group II: 〜られる (見る→見られる). する→される, くる→こられる. Very common in business reports ('was decided', 'was postponed').",
    more:[{jp:"契約は来月結ばれます。",en:"The contract will be signed next month."},{jp:"この製品は多くのお客様に使われています。",en:"This product is used by many customers."}]},
  {l:"N4",t:"使役 (causative)",en:"〜せる/させる — make/let someone do",
    ex:"部下に報告させました。",ex_en:"I had my subordinate report.",
    breakdown:"Causative = make/let someone do X. Group I: 〜せる (書く→書かせる). Group II: 〜させる (見る→見させる). する→させる, くる→こさせる. Used for delegation/supervision.",
    more:[{jp:"部下に資料を準備させました。",en:"I had my subordinate prepare the materials."},{jp:"社長が新製品を発表させました。",en:"The president had the new product announced."}]},

  {l:"N3",t:"〜ていただく / てもらう",en:"Receive the favor of someone doing X (humble when いただく)",
    ex:"ご確認いただきたく存じます。",ex_en:"I'd like you to confirm (humble).",
    breakdown:"Someone does X as a favor for you. てもらう = casual; ていただく = humble (toward superiors/clients). Pattern: [person] に [verb-て] いただく. Ubiquitous in business emails.",
    more:[{jp:"田中さんに資料を送っていただきました。",en:"Tanaka sent me the materials (as a favor)."},{jp:"ご検討いただければ幸いです。",en:"I'd appreciate it if you could consider it."}]},
  {l:"N3",t:"〜させていただく",en:"Humbly do X (very common business humble)",
    ex:"参加させていただきます。",ex_en:"I humbly will participate.",
    breakdown:"Causative + いただく = 'I humbly receive permission to do X'. The workhorse humble form in business. Slightly verbose — don't over-stack it (avoid 二重敬語).",
    more:[{jp:"明日、お休みさせていただきます。",en:"I will humbly take tomorrow off."},{jp:"ご確認させていただきます。",en:"I will humbly check."}]},
  {l:"N3",t:"〜お/ご〜する (謙譲)",en:"Humble: お+Vstem+する / ご+N+する",
    ex:"ご案内いたします。",ex_en:"I'll humbly guide you.",
    breakdown:"お + verb stem + する (or ご + noun + する) lowers YOUR action toward the listener. E.g. お持ちする, ご連絡する. With いたします (humble する) it's even more polite.",
    more:[{jp:"お持ちします。",en:"I'll carry it (humble)."},{jp:"ご報告いたします。",en:"I will humbly report."}]},
  {l:"N3",t:"〜お/ご〜になる (尊敬)",en:"Respect: raise the client's action",
    ex:"ご覧になりましたか。",ex_en:"Did you see it? (respect)",
    breakdown:"お + verb stem + になる (or ご + noun + になる) raises the SUPERIOR'S/CLIENT'S action. Never use it for your own actions. Special verbs replace this (いらっしゃる, おっしゃる, ご覧になる).",
    more:[{jp:"社長はもうお帰りになりました。",en:"The president has already gone home (respect)."},{jp:"資料はご覧になりましたか。",en:"Have you looked at the materials (respect)?"}]},
  {l:"N3",t:"〜ております",en:"Humble ている (ongoing humble state)",
    ex:"今、確認しております。",ex_en:"I'm confirming now (humble).",
    breakdown:"て + おります (humble いる) = humble version of ている. Describes your ongoing/state actions politely. Staple of business speech and emails.",
    more:[{jp:"今、資料を準備しております。",en:"I'm preparing the materials now (humble)."},{jp:"弊社は東京にございます。",en:"Our company is in Tokyo (humble あります)."}]},
  {l:"N3",t:"〜と存じます",en:"Humble 思う (I think — formal)",
    ex:"それがよいかと存じます。",ex_en:"I think that would be good (humble).",
    breakdown:"と存じます = humble 'I think'. Use instead of と思います in formal business to sound refined. Pattern: [plain sentence] と存じます.",
    more:[{jp:"この案が最適かと存じます。",en:"I think this plan is the best."},{jp:"問題ないかと存じます。",en:"I think there's no problem."}]},
  {l:"N3",t:"〜について / に関して",en:"About / concerning",
    ex:"契約についてご相談したいです。",ex_en:"I want to consult about the contract.",
    breakdown:"Noun + について = 'about/regarding X'. に関して is more formal — used in writing. Both let you state the topic of a sentence.",
    more:[{jp:"新製品についてご説明します。",en:"I'll explain about the new product."},{jp:"本件に関してご相談があります。",en:"I have something to consult about regarding this matter."}]},
  {l:"N3",t:"〜にしたがって / 〜につれて",en:"As X changes, Y changes",
    ex:"時間がたつにつれて、忘れます。",ex_en:"As time passes, I forget.",
    breakdown:"につれて / にしたがって = 'as X changes, Y also changes' — proportional change over time. にしたがって can also mean 'according to/following' (rules).",
    more:[{jp:"時代が変わるにつれて、言葉も変わります。",en:"As times change, language changes too."},{jp:"規則にしたがって行動してください。",en:"Please act according to the rules."}]},
  {l:"N3",t:"〜ばかり",en:"Only / just / nothing but",
    ex:"文句ばかり言っています。",ex_en:"They only complain.",
    breakdown:"Noun/verb (ta-form) + ばかり = 'only / nothing but X' (often with a negative/dismissive tone). For 'just did X' (recently), use 〜たばかり (e.g. 入社したばかり).",
    more:[{jp:"甘いものばかり食べています。",en:"I eat only sweet things."},{jp:"入社したばかりです。",en:"I just joined the company."}]},
  {l:"N3",t:"〜ようになる",en:"Come to do / become able to",
    ex:"日本語が話せるようになりました。",ex_en:"I've become able to speak Japanese.",
    breakdown:"Plain potential/verb + ようになる = 'reach the state where I can do X' — a change over time/practice. Marks progress. Negative: 〜ないようになる (come to not).",
    more:[{jp:"少しずつ漢字が読めるようになりました。",en:"I've gradually become able to read kanji."},{jp:"メールが一人で書けるようになります。",en:"You'll come to write emails by yourself."}]},
  {l:"N3",t:"〜ようにする",en:"Make sure to do / try to",
    ex:"毎日復習するようにしています。",ex_en:"I make sure to review daily.",
    breakdown:"Plain form + ようにする = 'make it a habit/rule to do X' / 'try to do X'. Focuses on your effort/intention. Negative: 〜ないようにする (try not to).",
    more:[{jp:"毎朝単語を覚えるようにしています。",en:"I make a point of memorizing vocab every morning."},{jp:"遅刻しないようにしてください。",en:"Please make sure not to be late."}]},
  {l:"N3",t:"〜らしい / 〜そう (hearsay/appearance)",en:"Apparently / looks like",
    ex:"来週発表されるらしいです。",ex_en:"Apparently it'll be announced next week.",
    breakdown:"らしい = 'apparently / I heard' (based on rumor). 〜そうです (after verb stem) = 'looks like it will' (appearance). 〜そうです (after plain) = 'I heard that'.",
    more:[{jp:"田中さんは来月帰国するらしいです。",en:"I hear Tanaka will return next month."},{jp:"雨が降りそうです。",en:"It looks like it's going to rain."}]},
  {l:"N3",t:"〜条件下で / 〜際に",en:"Under conditions / when (formal)",
    ex:"契約締結の際に、署名が必要です。",ex_en:"When signing the contract, a signature is needed.",
    breakdown:"際に = 'at the time of / when X happens' — formal version of 時. 〜条件下で = 'under the condition of X'. Both are business-writing staples.",
    more:[{jp:"お申し込みの際に、身分証が必要です。",en:"When applying, ID is required."},{jp:"この条件下で進めます。",en:"We'll proceed under these conditions."}]},
  {l:"N3",t:"〜に基づいて",en:"Based on",
    ex:"データに基づいて判断します。",ex_en:"We judge based on data.",
    breakdown:"Noun + に基づいて (もとづいて) = 'based on / according to X'. Formal; common in reports and decision-making statements.",
    more:[{jp:"ルールに基づいて判断します。",en:"We judge based on the rules."},{jp:"事実に基づいて報告します。",en:"We report based on facts."}]},
  {l:"N3",t:"〜に対して",en:"Toward / against (target)",
    ex:"お客様に対して丁寧に話す。",ex_en:"Speak politely toward customers.",
    breakdown:"Noun + に対して = 'toward / to / against X' — marks the target of an attitude/action. Versatile in business. に対する modifies a noun (Xに対する = 'toward X').",
    more:[{jp:"上司に対して失礼なことを言わないでください。",en:"Don't say rude things to your boss."},{jp:"お客様に対する態度が大切です。",en:"Attitude toward customers is important."}]}
];

// ---------- 26-WEEK CURRICULUM (6 months) ----------
// Phase 1 (W1-4): Foundations. Phase 2 (W5-12): Core grammar+vocab. Phase 3 (W13-20): Business+keigo. Phase 4 (W21-26): Output & fluency.
const CURRICULUM = [
  {w:1,phase:"基礎",title:"Kana + Greetings + Self-intro",goal:"Hiragana/Katakana fluent. Business greetings, はじめまして, name+company intro.",
    tasks:["Learn hiragana (Quiz kana tab)","Learn katakana","Drill: はじめまして、〇〇と申します","SRS: start with 10 new vocab/day","Shadowing: 5 mins greeting audio"]},
  {w:2,phase:"基礎",title:"Numbers, counters, prices",goal:"Count 1-100,000,000. Counters 枚/件/名/社. Prices.",
    tasks:["Numbers to 一億","Counters deck","Practice quoting prices","10 new vocab/day"]},
  {w:3,phase:"基礎",title:"Polite ます/です + particles",goal:"Solid N5 polite forms + core particles.",
    tasks:["Grammar: は/が/を/に/で/と","ます/です/ました drills","Write 5 self-intro sentences","10 vocab/day"]},
  {w:4,phase:"基礎",title:"Daily routine + te-form",goal:"Te-form requests, ている, time expressions.",
    tasks:["Te-form conjugation drill","〜てください requests","Describe your workday in JP","10 vocab/day; Review all W1-4"]},

  {w:5,phase:"核心",title:"Permission & obligation",goal:"〜てもいい/〜てはいけない/〜ないといけない.",
    tasks:["Permission grammar deck","Roleplay: asking permission","5 grammar points","10 vocab/day"]},
  {w:6,phase:"核心",title:"Ability & experience",goal:"〜ことができる / 〜たことがある / 〜つもり.",
    tasks:["Ability/experience drills","Talk about past work experience","5 grammar points","10 vocab/day"]},
  {w:7,phase:"核心",title:"Conditionals & conjecture",goal:"〜と / 〜たら / 〜ば / 〜でしょう.",
    tasks:["Conditional drills","Forecast exercises (〜でしょう)","5 grammar points","10 vocab/day"]},
  {w:8,phase:"核心",title:"Passive & causative",goal:"受身 & 使役 — key for business reporting.",
    tasks:["Passive drills (延期されました)","Causative drills","Read a short business report","10 vocab/day; Mid checkpoint"]},
  {w:9,phase:"核心",title:"Business vocab deep-dive I",goal:"Meeting vocab + office vocab (40 cards).",
    tasks:["Meeting+office decks","Describe your department","5 grammar points","10 vocab/day"]},
  {w:10,phase:"核心",title:"Business vocab deep-dive II",goal:"Finance vocab + email vocab (40 cards).",
    tasks:["Finance+email decks","Write a sample quote","5 grammar points","10 vocab/day"]},
  {w:11,phase:"核心",title:"Polite connectives",goal:"〜ので / 〜のに / 〜ために / 〜はず.",
    tasks:["Connective drills","Write 5 'because/although' biz sentences","5 grammar points","10 vocab/day"]},
  {w:12,phase:"核心",title:"Review & consolidation",goal:"All N5+N4 solid. Mock self-test.",
    tasks:["Full SRS review sweep","Self-test 1 (see Progress tab)","Re-weak grammar points","Read NHK Easy News article"]},

  {w:13,phase:"ビジネス",title:"Keigo foundations",goal:"丁寧語 vs 尊敬 vs 謙譲. 3 categories clear.",
    tasks:["Keigo tab: read rules","Memorize 8 core verb trios","Drill: raise vs lower","10 vocab/day"]},
  {w:14,phase:"ビジネス",title:"Humble structures",goal:"〜させていただく / お〜する / ご〜する.",
    tasks:["Humble structure drills","Rewrite casual sentences to humble","10 vocab/day"]},
  {w:15,phase:"ビジネス",title:"Respect structures",goal:"お〜になる / ご〜になる / special verbs.",
    tasks:["Respect structure drills","Describe a client's actions politely","10 vocab/day"]},
  {w:16,phase:"ビジネス",title:"Keigo mistakes & correction",goal:"Avoid the 8 common keigo errors.",
    tasks:["Mistakes tab: drill all 8","Find errors in sample emails","10 vocab/day"]},
  {w:17,phase:"ビジネス",title:"Email Japanese",goal:"20 email phrases internalized.",
    tasks:["Email phrase deck (20)","Write a full client email","10 vocab/day"]},
  {w:18,phase:"ビジネス",title:"Meeting Japanese",goal:"20 meeting phrases; run a mock meeting.",
    tasks:["Meeting phrase deck (20)","Mock-meeting roleplay (speak aloud)","10 vocab/day"]},
  {w:19,phase:"ビジネス",title:"Phone Japanese",goal:"15 phone phrases; mock phone calls.",
    tasks:["Phone phrase deck (15)","Mock phone call roleplay","10 vocab/day"]},
  {w:20,phase:"ビジネス",title:"Meishi & first meetings",goal:"名刺 exchange ritual + first-meeting scripts.",
    tasks:["Meishi phrase deck","Practice meishi ritual physically","Self-test 2","10 vocab/day"]},

  {w:21,phase:"応用",title:"Shadowing intensive",goal:"20 mins/day shadowing native business audio.",
    tasks:["Shadowing 20min/day","Record yourself, compare","Read 2 business articles","Review weak cards"]},
  {w:22,phase:"応用",title:"Output: speaking",goal:"iTalki/roleplay 2 sessions. Think aloud in JP.",
    tasks:["2 speaking sessions (tutor/roleplay)","5-min daily monologue in JP","10 vocab/day"]},
  {w:23,phase:"応用",title:"Output: writing",goal:"Write 5 emails + 1 short report.",
    tasks:["Write 5 client emails","Write 1 short report (200字)","Get corrections (Lang-8/ChatGPT)","Review"]},
  {w:24,phase:"応用",title:"Listening immersion",goal:"Podcasts/business videos daily.",
    tasks:["Podcast 30min/day (NHKビジネス)","Transcribe 3 min of audio","Review weak grammar","Self-test 3"]},
  {w:25,phase:"応用",title:"Keigo in real scenarios",goal:"Apply keigo in simulated negotiations.",
    tasks:["Negotiation roleplay","Apologize/politely decline drills","Review all keigo trios","10 vocab/day"]},
  {w:26,phase:"応用",title:"Fluency check & maintenance plan",goal:"Self-assess BJT-style. Lock daily routine.",
    tasks:["BJT-style self-test","Record 5-min self-intro+role","Write maintenance plan (SRS 20/day, immersion)","CELEBRATE, set 6-month+ plan"]}
];

// ---------- WORD OF THE DAY POOL (rotates; 30 high-leverage) ----------
const WORD_POOL = [
  {jp:"御社",reading:"おんしゃ",en:"your company (spoken)",why:"Use in speech; in writing use 貴社 (きしゃ)."},
  {jp:"弊社",reading:"へいしゃ",en:"our company (humble)",why:"Always humble when referring to your own company to a client."},
  {jp:"伺う",reading:"うかがう",en:"to visit/hear/ask (humble)",why:"Humble of 行く/来る/聞く. Tri-use verb."},
  {jp:"拝見する",reading:"はいけんする",en:"to look at (humble)",why:"Humble of 見る. 'I saw your email' = メールを拝見しました."},
  {jp:"申し上げる",reading:"もうしあげる",en:"to say (humble, formal)",why:"お礼申し上げます = I humbly thank you."},
  {jp:"承知いたしました",reading:"しょうちいたしました",en:"Understood (formal)",why:"Replace わかりました with clients."},
  {jp:"お疲れ様です",reading:"おつかれさまです",en:"Good work (greeting)",why:"Standard internal greeting. NEVER ご苦労様 to superiors."},
  {jp:"お世話になっております",reading:"おせわになっております",en:"Thank you for your support",why:"Standard email/phone opener to clients."},
  {jp:"恐れ入ります",reading:"おそれいります",en:"Excuse me (very polite)",why:"Use before a request to a stranger/superior."},
  {jp:"ご確認",reading:"ごかくにん",en:"confirmation (polite)",why:"ご確認ください / ご確認いただけますか."},
  {jp:"見積もり",reading:"みつもり",en:"quote/estimate",why:"Core sales word. 見積もりを送ります."},
  {jp:"納期",reading:"のうき",en:"delivery date",why:"Often the crux of negotiation."},
  {jp:"在庫",reading:"ざいこ",en:"inventory/stock",why:"在庫がありません = out of stock."},
  {jp:"締め切り",reading:"しめきり",en:"deadline",why:"締め切りは金曜です."},
  {jp:"延期",reading:"えんき",en:"postponement",why:"会議を延期します. Passive: 延期されました."},
  {jp:"検討",reading:"けんとう",en:"consideration",why:"検討します = 'we'll consider' (often = soft no)."},
  {jp:"承認",reading:"しょうにん",en:"approval",why:"承認を得る = get approval. Also = 'signature' on a doc."},
  {jp:"議事録",reading:"ぎじろく",en:"meeting minutes",why:"議事録をとる = take minutes."},
  {jp:"担当",reading:"たんとう",en:"in charge of",why:"〇〇を担当しています = I handle XX."},
  {jp:"出張",reading:"しゅっちょう",en:"business trip",why:"出張で大阪へ行きます."},
  {jp:"残業",reading:"ざんぎょう",en:"overtime",why:"残業があります = I have overtime."},
  {jp:"取引先",reading:"とりひきさき",en:"client/business partner",why:"Different from お客様 (customer)."},
  {jp:"部長",reading:"ぶちょう",en:"department head",why:"Common addressee. 部長、お疲れ様です."},
  {jp:"課長",reading:"かちょう",en:"section manager",why:"Below 部長. Common title."},
  {jp:"社長",reading:"しゃちょう",en:"company president",why:"Top. Use with respect, never casually."},
  {jp:"よろしくお願いします",reading:"よろしくおねがいします",en:"Please / I count on you",why:"Universal closer. Learn many variants."},
  {jp:"失礼します",reading:"しつれいします",en:"Excuse me (entering/leaving)",why:"Said entering/leaving rooms, hanging up."},
  {jp:"お先に失礼します",reading:"おさきにしつれいします",en:"I'm leaving first (polite)",why:"When leaving before colleagues."},
  {jp:"ご案内",reading:"ごあんない",en:"guide/information (polite)",why:"ご案内いたします = I'll humbly guide you."},
  {jp:"かしこまりました",reading:"かしこまりました",en:"Certainly (accepting request)",why:"Formal 'yes, understood' to clients."}
];

// ---------- QUIZ QUESTIONS (generated dynamically from decks; seeded below) ----------
const QUIZ_SEED = [
  // vocab→meaning, meaning→vocab, keigo, phrases
];

// expose
window.DATA = {HIRAGANA,KATAKANA,VOCAB,KEIGO_TRIO,KEIGO_RULES,KEIGO_MISTAKES,PHRASES,GRAMMAR,CURRICULUM,WORD_POOL};